version: '3.8'
services:
  app:
    build: ./php
    container_name: laravel-app
    volumes:
      - ./laravel-app:/var/www/html
    ports:
      - 8132:8132
    restart: unless-stopped
    networks:
      - laravel
    depends_on:
      - db

  db:
    image: postgres:16.2-bookworm
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - laravel

volumes:
  db_data:

networks:
  laravel:

