version: '3.8'
services:
  server:
    build: ./nginx
    container_name: nginx-server
    ports:
      - 3793:3793
    volumes:
      - ./laravel-app:/var/www/html
    networks:
      - laravel
    depends_on:
      - app
    
  app:
    build: ./php
    container_name: ng-laravel-app
    volumes:
      - ./laravel-app:/var/www/html
    expose:
      - 9000
    restart: unless-stopped
    networks:
      - laravel
#    depends_on:
#      - db

#  db:
#    image: postgres:16.2-bookworm
#    container_name: ng-postgres-db
#    restart: unless-stopped
#    environment:
#      POSTGRES_DB: laravel
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#    volumes:
#      - db_data:/var/lib/postgresql/data
#    networks:
#      - laravel

volumes:
  db_data:

networks:
  laravel:

